FORMAT: 1A


# MajesticThai

MajesticThai is a simple API allowing customers to view our menu and order through the Majestic Thai website.

## Menu Collection [/menu]

### List Menu [GET]

+ Response 200 (application/json)

        {
        [
            {
                "menu": "Majestic Thai Menu",
                "published_at": "2015-08-05T08:40:51.620Z",
                "menu":[
                    {
                        "title": "Summer Roll",
                        "description": "fresh spring roll with bean sauce.",
                        "price": 4.50,
                        "category": "appetizers",
                        
                    }, {
                        "title": "Grilled Chicken Satay",
                        "description": "on skewers, coconut milk-turmeric, peanut sauce",
                        "price": 8.00,
                        "category": "appetizers"

                    }, {
                        "title": "Steamed Vegetable Dumplings",
                        "description": "peanut, tofu, spinach, garlic chip, ginger soy dip",
                        "price": 8.00,
                        "category": "appetizers"
                    }, {
                        "title": "Chicken Curry Puffs",
                        "description": "caramelized chicken, onion, sweet potato, cucumber relish",
                        "price": 8.00,
                        "category": "appetizers"
                    },{
                        "title": "Vegetable Spring Rolls",
                        "description": "shitake mushroom, jicama, glass noodles, thai chili plum sauce",
                        "price": 7.00,
                        "category": "appetizers"
                    },{
                        "title": "Crispy Tofu",
                        "description": "peanut, tamarind-chili gastrique",
                        "price": 7.00,
                        "category": "appetizers"
                    },{
                        "title": "Green Papaya Salad",
                        "description": "dried shrimp, tomato, peanut, long bean, thai chili, lime juice",
                        "price": 10.00,
                        "category": "appetizers"
                       }, {
                        "title": "Fried Rice With Lump Crab Meat",
                        "description": "egg, chinese broccoli, tomato, scallion, onion, light soy sauce",
                        "price": 14.00,
                        "category": "entrée"

                    }, {
                        "title": "Jungle Curry Fried Rice With Chicken",
                        "description": "long hot chili, string bean, snow pea, thai basil, jungle curry sauce",
                        "price": 12.00,
                        "category": "entrée"
                    }, {
                        "title": "Pad Thai With Shrimp",
                        "description": "rice noodles, dried shrimp, peanut, egg, bean sprout, scallion, tamarind sauce",
                        "price": 13.00,
                        "category": "entrée"
                    },{
                        "title": "Pad See Ew With Beef",
                        "description": "(vermicelli or ﬂat noodles) chinese broccoli, cauliﬂower, egg",
                        "price": 13.00,
                        "category": "entrée"
                    },{
                        "title": "Pad Kee Moa With Chicken",
                        "description": "ﬂat rice noodles, tomato, baby bok choy, snow pea, chili puree, thai basil",
                        "price": 12.00,
                        "category": "entrée"
                    },{
                        "title": "Pad Woon Sen With Vegetable",
                        "description": "glass noodles, shitake mushroom, sugar snap pea, yu choy, napa cabbage, asian celery, sesame ginger soy",
                        "price": 13.00,
                        "category": "entrée"
                     },{
                        "title": "Ratchaburi Crab & Pork Dry Noodles",
                        "description": "handmade egg noodles, roasted pork, lump crab meat, yu choy, scallion",
                        "price": 13.00,
                        "category": "entrée"
                    },{
                        "title": "Pa-Yao Beef Noodles Soup",
                        "description": "vermicelli, braised beef, chinese broccoli, asian celery, bean sprout, meat ball, galangal pandan broth",
                        "price": 13.00,
                        "category": "entrée"
                    },{
                        "title": "Nakorn-Patom Duck Noodles Soup",
                        "description": "thin rice noodles, braised duck meat, asian celery, bean sprout, ﬁve spice soy broth",
                        "price": 13.00,
                        "category": "entrée"
                    },{
                        "title": "Pad Kee Moa With Chicken",
                        "description": "ﬂat rice noodles, tomato, baby bok choy, snow pea, chili puree, thai basil",
                        "price": 12.00,
                        "category": "entrée"
                    },{
                        "title": "House Roasted Pork",
                        "description": "Compliments our Pa-Yo Beef Noodles Soup",
                        "price": 4.95,
                        "category": "Side Orders"
                     },{
                        "title": "Jasmine White Rice",
                        "description": "Compliments all our pork dishes",
                        "price": 1.95,
                        "category": "Side Orders"
                    },{
                        "title": "Sticky Rice",
                        "description": "a ",
                        "price": 13.00,
                        "category": "entrée"
                    },{
                        "title": "Nakorn-Patom Duck Noodles Soup",
                        "description": "thin rice noodles, braised duck meat, asian celery, bean sprout, ﬁve spice soy broth",
                        "price": 13.00,
                        "category": "entrée"
                    }
                ]
            }


## Menu Item [/menu/{title}]


### Get an individual menu item [GET]

You may get an individual meni item using this action. It takes a JSON
object containing a menu item.


+ Response 200 (application/json)

    
        {
                       "title": "Summer Roll",
                        "description": "fresh spring roll with bean sauce.",
                        "price": 4.50,
                        "category": "appetizers",
                        "review": "Delicious!"
                    },
        

## Order Listing [/orders]


### Get a listing of orders  [GET]

Each order should return as an object with the order's id, username, time, total, and array of ordered items


+ Response 200 (application/json)

         "orders":       [
                    {
                        "id": 1,
                        "username": "DanDude",
                        "time": 11:45,
                        "total": 23.45,
                        "estimated-completion": 15
                        "ordered": [ 
                                { 
                                "title": "Grilled Chicken Satay",
                                "description": "on skewers, coconut milk-turmeric, peanut sauce",
                                "price": 8.00,
                                "category": "appetizers"
                                }, {
                                "title": "Grilled Chicken Satay",
                                "description": "on skewers, coconut milk-turmeric, peanut sauce",
                                "price": 8.00,
                                "category": "appetizers"
                                
                                } ]
                        
                    }, {
                        "id": 2,
                        "username": "GabeDude",
                        "time": 12:45,
                        "total": 18.45,
                        "estimated-completion": 20,
                        "ordered": [ 
                                { 
                                "title": "Grilled Chicken Satay",
                                "description": "on skewers, coconut milk-turmeric, peanut sauce",
                                "price": 8.00,
                                "category": "appetizers"
                                }, {
                                "title": "Grilled Chicken Satay",
                                "description": "on skewers, coconut milk-turmeric, peanut sauce",
                                "price": 8.00,
                                "category": "appetizers"
                                
                                } ]
                        
                    }
                    
                ]